use std::collections::HashSet;

use heck::{ToLowerCamelCase, ToSnakeCase};
use sov_universal_wallet::ty::Ty;

use super::type_mapper;
use super::{ActionGroup, SchemaInfo, SchemaStruct};

/// Namespace descriptions for doc comments.
fn namespace_doc(name: &str) -> &'static str {
    match name {
        "User" => "User trading operations (deposit, withdraw, orders, vaults, etc.).",
        "Public" => "Permissionless operations anyone can call (liquidations, funding, etc.).",
        "Keeper" => "Keeper-only operations (oracle prices, funding rates, fee tiers, etc.).",
        "Vault" => "Vault leader operations (config, withdrawals, delegation, etc.).",
        "Admin" => "Admin-only operations (market init, global config, force actions, etc.).",
        _ => "Exchange operations.",
    }
}

/// Emit the full generated source code: struct wrappers + namespace factory methods.
pub fn emit_all(info: &SchemaInfo) -> String {
    let schema = bullet_exchange_interface::schema::Schema::of_single_type::<
        bullet_exchange_interface::transaction::Transaction,
    >()
    .expect("failed to build schema");
    let types = schema.types();
    let wrapper_indices = type_mapper::wrapped_struct_indices(&info.structs);
    let enum_indices = type_mapper::wrapped_enum_indices(&info.enums);

    let mut out = String::new();

    out.push_str("// Auto-generated by build.rs — do not edit manually.\n\n");

    // Helper function for extracting typed elements from js_sys::Array.
    // Uses TryFromJsValue which is auto-generated by #[wasm_bindgen] on exported structs.
    out.push_str("fn extract_array<T: wasm_bindgen::convert::TryFromJsValue>(arr: js_sys::Array) -> Result<Vec<T>, String> {\n");
    out.push_str("    arr.iter()\n");
    out.push_str("        .map(|v| T::try_from_js_value(v).map_err(|_| format!(\"expected {}\", std::any::type_name::<T>())))\n");
    out.push_str("        .collect()\n");
    out.push_str("}\n\n");

    // Emit enum wrappers.
    for e in &info.enums {
        out.push_str(&emit_enum_wrapper(e));
        out.push('\n');
    }

    // Emit struct wrappers.
    for s in &info.structs {
        out.push_str(&emit_struct_wrapper(
            s,
            types,
            &wrapper_indices,
            &enum_indices,
        ));
        out.push('\n');
    }

    // Emit namespace factory methods.
    for group in &info.action_groups {
        out.push_str(&emit_group(group, types, &wrapper_indices, &enum_indices));
        out.push('\n');
    }

    out
}

// ── Struct wrapper emission ──────────────────────────────────────────────────

fn emit_struct_wrapper(
    s: &SchemaStruct,
    types: &[Ty<sov_universal_wallet::schema::IndexLinking>],
    wrapper_indices: &HashSet<usize>,
    enum_indices: &HashSet<usize>,
) -> String {
    let type_name = &s.type_name;
    let wrapper_name = format!("Wasm{type_name}");
    let js_name = type_name; // JS sees the original name without Wasm prefix

    // Some types are generic over Address. We need the concrete type for field declarations,
    // but struct literal expressions don't use generic params (inferred from context).
    let inner_type_decl = match type_name.as_str() {
        "CreateVaultArgs" | "UpdateGlobalConfigArgs" => format!("{type_name}<Address>"),
        _ => type_name.clone(),
    };
    // For struct literal expressions (initializers), always use the bare name.
    let inner_type_init = type_name;

    let mappings = type_mapper::map_fields(&s.fields, types, wrapper_indices, enum_indices);

    // Sort: required params first, optional last.
    let mut field_order: Vec<usize> = (0..s.fields.len()).collect();
    field_order.sort_by_key(|&i| mappings[i].is_optional as u8);

    // Build constructor params.
    let params: Vec<String> = field_order
        .iter()
        .map(|&i| {
            let f = &s.fields[i];
            let m = &mappings[i];
            format!("{}: {}", f.name, m.param_type)
        })
        .collect();
    let params_str = params.join(", ");

    // Build field assignments (original field order).
    let assignments: Vec<String> = s
        .fields
        .iter()
        .zip(mappings.iter())
        .map(|(f, m)| {
            let converted = m.conversion.replace("{v}", &f.name);
            if converted == f.name {
                format!("                {}", f.name)
            } else {
                format!("                {}: {}", f.name, converted)
            }
        })
        .collect();

    let mut out = String::new();

    // Struct definition.
    out.push_str(&format!(
        "/// Wrapper for `{type_name}`.\n\
         #[wasm_bindgen(js_name = {js_name})]\n\
         pub struct {wrapper_name} {{\n\
         \x20   pub(crate) inner: {inner_type_decl},\n\
         }}\n\n"
    ));

    // Constructor impl.
    out.push_str(&format!(
        "#[wasm_bindgen(js_class = {js_name})]\n\
         impl {wrapper_name} {{\n\
         \x20   #[wasm_bindgen(constructor)]\n\
         \x20   pub fn new({params_str}) -> WasmResult<{wrapper_name}> {{\n\
         \x20       Ok({wrapper_name} {{\n\
         \x20           inner: {inner_type_init} {{\n\
         {}\n\
         \x20           }},\n\
         \x20       }})\n\
         \x20   }}\n\
         }}\n",
        assignments.join(",\n")
    ));

    out
}

// ── Namespace factory method emission ────────────────────────────────────────

fn emit_group(
    group: &ActionGroup,
    types: &[Ty<sov_universal_wallet::schema::IndexLinking>],
    wrapper_indices: &HashSet<usize>,
    enum_indices: &HashSet<usize>,
) -> String {
    let ns = &group.call_message_variant;
    let doc = namespace_doc(ns);

    let mut out = String::new();

    out.push_str(&format!("/// {doc}\n"));
    out.push_str("#[wasm_bindgen]\n");
    out.push_str(&format!("pub struct {ns};\n\n"));

    out.push_str("#[wasm_bindgen]\n");
    out.push_str(&format!("impl {ns} {{\n"));

    for variant in &group.variants {
        out.push_str(&emit_variant(
            group,
            variant,
            types,
            wrapper_indices,
            enum_indices,
        ));
    }

    out.push_str("}\n");
    out
}

fn emit_variant(
    group: &ActionGroup,
    variant: &super::VariantInfo,
    types: &[Ty<sov_universal_wallet::schema::IndexLinking>],
    wrapper_indices: &HashSet<usize>,
    enum_indices: &HashSet<usize>,
) -> String {
    let mappings = type_mapper::map_fields(&variant.fields, types, wrapper_indices, enum_indices);

    let rust_fn_name = variant.variant_name.to_snake_case();
    let js_name = variant.variant_name.to_lower_camel_case();
    let action_enum = &group.action_enum;
    let cm_variant = &group.call_message_variant;
    let variant_name = &variant.variant_name;

    // Sort fields: required first, optional last.
    let mut field_order: Vec<usize> = (0..variant.fields.len()).collect();
    field_order.sort_by_key(|&i| mappings[i].is_optional as u8);

    // Build parameter list.
    let params: Vec<String> = field_order
        .iter()
        .map(|&i| {
            let f = &variant.fields[i];
            let m = &mappings[i];
            format!("{}: {}", f.name, m.param_type)
        })
        .collect();

    let params_str = params.join(", ");

    // Build field assignments in original field order.
    let assignments: Vec<String> = variant
        .fields
        .iter()
        .zip(mappings.iter())
        .map(|(f, m)| {
            let converted = m.conversion.replace("{v}", &f.name);
            if converted == f.name {
                format!("                {}", f.name)
            } else {
                format!("                {}: {}", f.name, converted)
            }
        })
        .collect();

    let body = if assignments.is_empty() {
        format!(
            "        Ok(WasmCallMessage {{\n\
             \x20           inner: CallMessage::{cm_variant}({action_enum}::{variant_name} {{}}),\n\
             \x20       }})"
        )
    } else {
        format!(
            "        Ok(WasmCallMessage {{\n\
             \x20           inner: CallMessage::{cm_variant}({action_enum}::{variant_name} {{\n\
             {}\n\
             \x20           }}),\n\
             \x20       }})",
            assignments.join(",\n")
        )
    };

    format!(
        "    #[wasm_bindgen(js_name = {js_name})]\n\
         \x20   pub fn {rust_fn_name}({params_str}) -> WasmResult<WasmCallMessage> {{\n\
         {body}\n\
         \x20   }}\n\n"
    )
}

// ── Enum wrapper emission ────────────────────────────────────────────────────

fn emit_enum_wrapper(e: &super::SchemaEnum) -> String {
    let type_name = &e.type_name;
    let wrapper_name = format!("Wasm{type_name}");

    let mut out = String::new();

    // wasm_bindgen C-style enum.
    out.push_str(&format!("#[wasm_bindgen(js_name = {type_name})]\n"));
    out.push_str("#[derive(Clone, Copy)]\n");
    out.push_str(&format!("pub enum {wrapper_name} {{\n"));
    for (i, variant) in e.variants.iter().enumerate() {
        out.push_str(&format!("    {variant} = {i},\n"));
    }
    out.push_str("}\n\n");

    // From<WasmEnum> -> domain enum via serde roundtrip.
    // wasm_bindgen enums are repr(u32), so we match on discriminant.
    out.push_str(&format!("impl {wrapper_name} {{\n"));
    out.push_str(&format!("    fn into_domain(self) -> {type_name} {{\n"));
    out.push_str("        match self {\n");
    for variant in &e.variants {
        out.push_str(&format!(
            "            {wrapper_name}::{variant} => {type_name}::{variant},\n"
        ));
    }
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out
}
