//! Emit generated Rust source code for wasm-bindgen types.

pub mod enums;
pub mod namespaces;
pub mod structs;

use super::map;
use super::{FieldInfo, SchemaInfo, Types};

/// Emit the complete generated source file.
pub fn emit_all(info: &SchemaInfo) -> String {
    let schema = bullet_exchange_interface::schema::Schema::of_single_type::<
        bullet_exchange_interface::transaction::Transaction,
    >()
    .expect("failed to build schema");
    let types = schema.types();
    let wrapper_indices = map::wrapped_struct_indices(&info.structs);
    let enum_indices = map::wrapped_enum_indices(&info.enums);

    let mut out = String::new();

    out.push_str("// Auto-generated by build.rs — do not edit manually.\n\n");

    // Helper for extracting typed elements from js_sys::Array.
    out.push_str(EXTRACT_ARRAY_HELPER);

    // Enums.
    for e in &info.enums {
        out.push_str(&enums::emit_enum(e));
        out.push('\n');
    }

    // Struct wrappers.
    for s in &info.structs {
        out.push_str(&structs::emit_struct(
            s,
            types,
            &wrapper_indices,
            &enum_indices,
        ));
        out.push('\n');
    }

    // Namespace factory methods.
    for group in &info.action_groups {
        out.push_str(&namespaces::emit_namespace(
            group,
            types,
            &wrapper_indices,
            &enum_indices,
        ));
        out.push('\n');
    }

    out
}

// ── Shared helpers ───────────────────────────────────────────────────────────

/// Build field assignment lines for a struct initializer.
/// Returns a joined string of `"                field: conversion"` lines.
fn field_assignments(fields: &[FieldInfo], mappings: &[map::ParamMapping]) -> String {
    fields
        .iter()
        .zip(mappings.iter())
        .map(|(f, m)| {
            let converted = m.conversion.replace("{v}", &f.name);
            if converted == f.name {
                format!("                {}", f.name)
            } else {
                format!("                {}: {}", f.name, converted)
            }
        })
        .collect::<Vec<_>>()
        .join(",\n")
}

const EXTRACT_ARRAY_HELPER: &str = "\
fn extract_array<T: wasm_bindgen::convert::TryFromJsValue>(arr: js_sys::Array) -> Result<Vec<T>, String> {
    arr.iter()
        .map(|v| T::try_from_js_value(v).map_err(|_| format!(\"expected {}\", std::any::type_name::<T>())))
        .collect()
}

";
