//! Emit generated Rust source code from resolved schema data.

pub mod enums;
pub mod namespaces;
pub mod structs;

use proc_macro2::TokenStream;
use quote::quote;

use super::{MappedField, SchemaInfo};

/// Emit the complete generated source file.
pub fn emit_all(info: &SchemaInfo) -> String {
    let helper = extract_array_helper();

    let enum_tokens: Vec<TokenStream> = info.enums.iter().map(enums::emit_enum).collect();
    let struct_tokens: Vec<TokenStream> = info.structs.iter().map(structs::emit_struct).collect();
    let namespace_tokens: Vec<TokenStream> = info
        .action_groups
        .iter()
        .map(namespaces::emit_namespace)
        .collect();

    let tokens = quote! {
        // Auto-generated by build.rs — do not edit manually.

        #helper

        #(#enum_tokens)*

        #(#struct_tokens)*

        #(#namespace_tokens)*
    };

    let ast = syn::parse2(tokens).expect("generated code should be valid Rust");
    prettyplease::unparse(&ast)
}

// ── Shared helpers ───────────────────────────────────────────────────────────

/// Build field assignment tokens for a struct initializer.
pub fn field_assignments(fields: &[MappedField]) -> Vec<TokenStream> {
    fields
        .iter()
        .map(|f| {
            let name = quote::format_ident!("{}", f.name);
            let converted = f.conversion.replace("{v}", &f.name);
            if converted == f.name {
                quote! { #name }
            } else {
                let conversion: TokenStream =
                    converted.parse().expect("conversion should be valid");
                quote! { #name: #conversion }
            }
        })
        .collect()
}

fn extract_array_helper() -> TokenStream {
    quote! {
        fn extract_array<T: wasm_bindgen::convert::TryFromJsValue>(arr: js_sys::Array) -> Result<Vec<T>, String> {
            arr.iter()
                .map(|v| T::try_from_js_value(v).map_err(|_| format!("expected {}", std::any::type_name::<T>())))
                .collect()
        }
    }
}
