//! Emit generated Rust source code from resolved schema data.

pub mod enums;
pub mod namespaces;
pub mod structs;

use proc_macro2::TokenStream;
use quote::quote;

use super::{MappedField, SchemaInfo};

pub struct EmittedParams {
    pub tokens: Vec<TokenStream>,
    pub jsdoc: Vec<String>,
}

/// Emit the complete generated source file.
pub fn emit_all(info: &SchemaInfo) -> String {
    let helper = extract_array_helper();

    let enum_tokens: Vec<TokenStream> = info.enums.iter().map(enums::emit_enum).collect();
    let struct_tokens: Vec<TokenStream> = info.structs.iter().map(structs::emit_struct).collect();
    let namespace_tokens: Vec<TokenStream> = info
        .action_groups
        .iter()
        .map(namespaces::emit_namespace)
        .collect();

    let tokens = quote! {
        // Auto-generated by build.rs — do not edit manually.

        #helper

        #(#enum_tokens)*

        #(#struct_tokens)*

        #(#namespace_tokens)*
    };

    let ast = syn::parse2(tokens).expect("generated code should be valid Rust");
    prettyplease::unparse(&ast)
}

// ── Shared helpers ───────────────────────────────────────────────────────────

/// Build field assignment tokens for a struct initializer.
pub fn field_assignments(fields: &[MappedField]) -> Vec<TokenStream> {
    fields
        .iter()
        .map(|f| {
            let name = quote::format_ident!("{}", f.name);
            let converted = f.conversion.replace("{v}", &f.name);
            if converted == f.name {
                quote! { #name }
            } else {
                let conversion: TokenStream =
                    converted.parse().expect("conversion should be valid");
                quote! { #name: #conversion }
            }
        })
        .collect()
}

/// Emit function parameters and matching JSDoc from the same ordered fields.
/// wasm-bindgen requires optional parameters to trail required parameters.
pub fn emitted_params(fields: &[MappedField]) -> EmittedParams {
    let mut field_order: Vec<usize> = (0..fields.len()).collect();
    field_order.sort_by_key(|&i| fields[i].is_optional as u8);

    let tokens = field_order
        .iter()
        .map(|&i| {
            let name = quote::format_ident!("{}", fields[i].name);
            let ty: TokenStream = fields[i]
                .param_type
                .parse()
                .expect("param type should parse");
            quote! { #name: #ty }
        })
        .collect();
    let jsdoc = field_order
        .iter()
        .map(|&i| {
            let field = &fields[i];
            let name = if field.is_optional {
                format!("[{}]", field.name)
            } else {
                field.name.clone()
            };
            format!(
                "@param {{{}}} {name} - Value for `{}`.",
                jsdoc_type(field),
                field.name
            )
        })
        .collect();

    EmittedParams { tokens, jsdoc }
}

fn jsdoc_type(field: &MappedField) -> String {
    field
        .jsdoc_type
        .clone()
        .unwrap_or_else(|| jsdoc_type_from_rust(&field.param_type))
}

fn jsdoc_type_from_rust(rust_type: &str) -> String {
    if let Some(inner) = rust_type
        .strip_prefix("Option<")
        .and_then(|ty| ty.strip_suffix('>'))
    {
        return jsdoc_type_from_rust(inner);
    }
    if let Some(inner) = rust_type
        .strip_prefix("Vec<")
        .and_then(|ty| ty.strip_suffix('>'))
    {
        return match inner {
            "u8" => "Uint8Array".into(),
            "u16" => "Uint16Array".into(),
            "u32" => "Uint32Array".into(),
            "u64" => "BigUint64Array".into(),
            "i16" => "Int16Array".into(),
            "i64" => "BigInt64Array".into(),
            other => format!("Array<{}>", jsdoc_type_from_rust(other)),
        };
    }

    match rust_type {
        "&str" | "String" => "string".into(),
        "bool" => "boolean".into(),
        "u8" | "u16" | "u32" | "i16" => "number".into(),
        "u64" | "i64" | "u128" => "bigint".into(),
        "js_sys::Array" => "Array<any>".into(),
        ty if ty.starts_with("Wasm") => ty.trim_start_matches("Wasm").into(),
        ty => ty.into(),
    }
}

fn extract_array_helper() -> TokenStream {
    quote! {
        fn extract_array<T: wasm_bindgen::convert::TryFromJsValue>(arr: js_sys::Array) -> Result<Vec<T>, String> {
            arr.iter()
                .map(|v| T::try_from_js_value(v).map_err(|_| format!("expected {}", std::any::type_name::<T>())))
                .collect()
        }
    }
}
