//! Emit side-effect-free JavaScript package subpaths.

use heck::{ToLowerCamelCase, ToSnakeCase};

use super::super::{ActionGroup, MappedField, SchemaEnum, SchemaInfo, SchemaStruct};

pub fn emit_calls_js(info: &SchemaInfo) -> String {
    let mut out = String::new();
    out.push_str(CALLS_JS_HEADER);
    out.push('\n');

    for group in &info.action_groups {
        emit_namespace_js(&mut out, group);
        out.push('\n');
    }

    out.push_str(WARP_JS);
    out
}

pub fn emit_calls_dts(info: &SchemaInfo) -> String {
    let mut out = calls_dts_header(info);

    for group in &info.action_groups {
        emit_namespace_dts(&mut out, group);
        out.push('\n');
    }

    out.push_str(WARP_DTS);
    out
}

pub fn emit_primitives_js(info: &SchemaInfo) -> String {
    let mut out = String::new();
    out.push_str(PRIMITIVES_JS_HEADER);
    out.push('\n');

    for e in &info.enums {
        emit_enum_js(&mut out, e);
        out.push('\n');
    }

    for s in &info.structs {
        emit_struct_js(&mut out, s);
        out.push('\n');
    }

    out
}

pub fn emit_primitives_dts(info: &SchemaInfo) -> String {
    let mut out = String::new();
    out.push_str(PRIMITIVES_DTS_HEADER);
    out.push('\n');

    for e in &info.enums {
        emit_enum_dts(&mut out, e);
        out.push('\n');
    }

    for s in &info.structs {
        emit_struct_dts(&mut out, s);
        out.push('\n');
    }

    out
}

pub fn emit_topics_js() -> &'static str {
    TOPICS_JS
}

pub fn emit_topics_dts() -> &'static str {
    TOPICS_DTS
}

pub fn emit_errors_js() -> &'static str {
    ERRORS_JS
}

pub fn emit_errors_dts() -> &'static str {
    ERRORS_DTS
}

fn calls_dts_header(info: &SchemaInfo) -> String {
    let imports = std::iter::once("JsonObject".to_string())
        .chain(info.enums.iter().map(|e| e.type_name.clone()))
        .chain(info.structs.iter().map(|s| s.type_name.clone()))
        .collect::<Vec<_>>()
        .join(", ");

    format!(
        r#"// Auto-generated by wasm/build.rs - do not edit manually.
import type {{ {imports} }} from "./primitives.js";
export type {{ JsonObject, JsonPrimitive, JsonValue }} from "./primitives.js";

export type RuntimeCallData = Readonly<JsonObject> & {{ readonly __brand?: "RuntimeCallData" }};

export declare function isRuntimeCallData(value: unknown): value is RuntimeCallData;
export declare function toRuntimeCallJson(call: RuntimeCallData): string;

"#
    )
}

fn emit_enum_js(out: &mut String, e: &SchemaEnum) {
    out.push_str(&format!("export const {} = Object.freeze({{\n", e.type_name));
    for variant in &e.variants {
        out.push_str(&format!("  {}: {},\n", variant, js_string(&variant.to_snake_case())));
    }
    out.push_str("});\n");
}

fn emit_enum_dts(out: &mut String, e: &SchemaEnum) {
    out.push_str(&format!("export declare const {}: {{\n", e.type_name));
    for variant in &e.variants {
        out.push_str(&format!(
            "  readonly {}: {};\n",
            variant,
            ts_string_literal(&variant.to_snake_case())
        ));
    }
    out.push_str("};\n");
    out.push_str(&format!(
        "export type {} = typeof {}[keyof typeof {}];\n",
        e.type_name, e.type_name, e.type_name
    ));
}

fn emit_struct_js(out: &mut String, s: &SchemaStruct) {
    let fields = ordered_fields(&s.fields);
    let params = fields
        .iter()
        .map(|f| if f.is_optional { format!("{} = undefined", f.name) } else { f.name.clone() })
        .collect::<Vec<_>>()
        .join(", ");
    let names = field_names_array(&fields);
    let values = fields.iter().map(|f| f.name.as_str()).collect::<Vec<_>>().join(", ");

    out.push_str(&format!("export class {} {{\n", s.type_name));
    out.push_str(&format!("  constructor({params}) {{\n"));
    out.push_str(&format!("    this.__value = makeFields({names}, [{values}]);\n"));
    out.push_str("    Object.freeze(this.__value);\n");
    out.push_str("  }\n");
    out.push_str("  toJSON() {\n");
    out.push_str("    return this.__value;\n");
    out.push_str("  }\n");
    out.push_str("}\n");
}

fn emit_struct_dts(out: &mut String, s: &SchemaStruct) {
    let params = ordered_fields(&s.fields).iter().map(ts_param).collect::<Vec<_>>().join(", ");

    out.push_str(&format!("export declare class {} {{\n", s.type_name));
    out.push_str(&format!("  constructor({params});\n"));
    out.push_str("  toJSON(): JsonObject;\n");
    out.push_str("}\n");
}

fn emit_namespace_js(out: &mut String, group: &ActionGroup) {
    out.push_str(&format!("export class {} {{\n", group.call_message_variant));
    for variant in &group.variants {
        let fields = ordered_fields(&variant.fields);
        let method = variant.variant_name.to_lower_camel_case();
        let action = variant.variant_name.to_snake_case();
        let group_name = group.call_message_variant.to_snake_case();
        let params = fields
            .iter()
            .map(|f| if f.is_optional { format!("{} = undefined", f.name) } else { f.name.clone() })
            .collect::<Vec<_>>()
            .join(", ");
        let names = field_names_array(&fields);
        let values = fields.iter().map(|f| f.name.as_str()).collect::<Vec<_>>().join(", ");

        out.push_str(&format!("  static {method}({params}) {{\n"));
        out.push_str(&format!(
            "    return makeExchangeCall({}, {}, {names}, [{values}]);\n",
            js_string(&group_name),
            js_string(&action)
        ));
        out.push_str("  }\n");
    }
    out.push_str("}\n");
}

fn emit_namespace_dts(out: &mut String, group: &ActionGroup) {
    out.push_str(&format!("export declare class {} {{\n", group.call_message_variant));
    for variant in &group.variants {
        let method = variant.variant_name.to_lower_camel_case();
        let params =
            ordered_fields(&variant.fields).iter().map(ts_param).collect::<Vec<_>>().join(", ");

        out.push_str(&format!("  static {method}({params}): RuntimeCallData;\n"));
    }
    out.push_str("}\n");
}

fn ordered_fields(fields: &[MappedField]) -> Vec<&MappedField> {
    let mut ordered = fields.iter().collect::<Vec<_>>();
    ordered.sort_by_key(|field| field.is_optional as u8);
    ordered
}

fn field_names_array(fields: &[&MappedField]) -> String {
    let values = fields.iter().map(|f| js_string(&f.name)).collect::<Vec<_>>().join(", ");
    format!("[{values}]")
}

fn ts_param(field: &&MappedField) -> String {
    let name = &field.name;
    let ty = ts_type(&field.param_type);
    if field.is_optional { format!("{name}?: {ty} | null") } else { format!("{name}: {ty}") }
}

fn ts_type(param_type: &str) -> String {
    let ty =
        param_type.strip_prefix("Option<").and_then(|v| v.strip_suffix('>')).unwrap_or(param_type);

    if let Some(inner) = ty.strip_prefix("Vec<").and_then(|v| v.strip_suffix('>')) {
        return match inner {
            "u8" => "Uint8Array | number[]".to_string(),
            "u64" => "BigUint64Array | bigint[] | number[]".to_string(),
            _ => format!("Array<{}>", ts_type(inner)),
        };
    }

    if ty.starts_with("Wasm") {
        return ty.trim_start_matches("Wasm").to_string();
    }

    match ty {
        "&str" | "String" => "string".to_string(),
        "bool" => "boolean".to_string(),
        "u64" | "u128" | "i64" => "bigint | number".to_string(),
        "u8" | "u16" | "u32" | "i16" => "number".to_string(),
        "js_sys::Array" => "Array<unknown>".to_string(),
        other => other.to_string(),
    }
}

fn js_string(value: &str) -> String {
    format!("{value:?}")
}

fn ts_string_literal(value: &str) -> String {
    js_string(value)
}

const PRIMITIVES_JS_HEADER: &str = r#"// Auto-generated by wasm/build.rs - do not edit manually.
function isObject(value) {
  return typeof value === "object" && value !== null;
}

function isTypedArray(value) {
  return ArrayBuffer.isView(value) && !(value instanceof DataView);
}

function normalizeValue(value) {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  if (typeof value === "bigint") {
    return value;
  }
  if (Array.isArray(value)) {
    return value.map(normalizeValue);
  }
  if (isTypedArray(value)) {
    return Array.from(value);
  }
  if (isObject(value) && typeof value.toJSON === "function") {
    return normalizeValue(value.toJSON());
  }
  if (isObject(value)) {
    const out = {};
    for (const [key, nested] of Object.entries(value)) {
      const normalized = normalizeValue(nested);
      if (normalized !== undefined) {
        out[key] = normalized;
      }
    }
    return out;
  }
  return value;
}

function makeFields(names, values) {
  const out = {};
  for (let i = 0; i < names.length; i += 1) {
    const normalized = normalizeValue(values[i]);
    if (normalized !== undefined) {
      out[names[i]] = normalized;
    }
  }
  return out;
}

"#;

const PRIMITIVES_DTS_HEADER: &str = r#"// Auto-generated by wasm/build.rs - do not edit manually.
export type JsonPrimitive = string | number | boolean | bigint | null;
export type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue };
export type JsonObject = { [key: string]: JsonValue };

"#;

const CALLS_JS_HEADER: &str = r#"// Auto-generated by wasm/build.rs - do not edit manually.
const RUNTIME_CALL_DATA = Symbol.for("@bulletxyz/sdk-wasm/calls/runtime-call");
const MAX_SAFE_INTEGER_BIGINT = BigInt(Number.MAX_SAFE_INTEGER);

function isObject(value) {
  return typeof value === "object" && value !== null;
}

function isTypedArray(value) {
  return ArrayBuffer.isView(value) && !(value instanceof DataView);
}

function normalizeValue(value) {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  if (typeof value === "bigint") {
    return value;
  }
  if (Array.isArray(value)) {
    return value.map(normalizeValue);
  }
  if (isTypedArray(value)) {
    return Array.from(value);
  }
  if (isObject(value) && typeof value.toJSON === "function") {
    return normalizeValue(value.toJSON());
  }
  if (isObject(value)) {
    const out = {};
    for (const [key, nested] of Object.entries(value)) {
      const normalized = normalizeValue(nested);
      if (normalized !== undefined) {
        out[key] = normalized;
      }
    }
    return out;
  }
  return value;
}

function normalizeForJson(value) {
  const normalized = normalizeValue(value);
  if (typeof normalized === "bigint") {
    if (normalized <= MAX_SAFE_INTEGER_BIGINT && normalized >= -MAX_SAFE_INTEGER_BIGINT) {
      return Number(normalized);
    }
    return normalized.toString();
  }
  if (Array.isArray(normalized)) {
    return normalized.map(normalizeForJson);
  }
  if (isObject(normalized)) {
    const out = {};
    for (const [key, nested] of Object.entries(normalized)) {
      out[key] = normalizeForJson(nested);
    }
    return out;
  }
  return normalized;
}

function brandCall(value) {
  Object.defineProperty(value, RUNTIME_CALL_DATA, {
    value: true,
    enumerable: false,
  });
  return Object.freeze(value);
}

function makeFields(names, values) {
  const out = {};
  for (let i = 0; i < names.length; i += 1) {
    const normalized = normalizeValue(values[i]);
    if (normalized !== undefined) {
      out[names[i]] = normalized;
    }
  }
  return out;
}

function makeExchangeCall(group, action, names, values) {
  return brandCall({
    exchange: {
      [group]: {
        [action]: makeFields(names, values),
      },
    },
  });
}

export function isRuntimeCallData(value) {
  return isObject(value)
    && (value[RUNTIME_CALL_DATA] === true
      || isObject(value.exchange)
      || isObject(value.warp)
      || isObject(value.bank));
}

export function toRuntimeCallJson(call) {
  return JSON.stringify(normalizeForJson(call));
}

"#;

const WARP_JS: &str = r#"function normalizeWarpAmount(value, fieldName) {
  if (typeof value === "bigint") {
    if (value < 0n) {
      throw new Error(`${fieldName} must be a non-negative integer`);
    }
    return value.toString();
  }
  if (typeof value === "number") {
    if (!Number.isFinite(value) || value < 0 || !Number.isInteger(value)) {
      throw new Error(`${fieldName} number must be a non-negative integer`);
    }
    if (!Number.isSafeInteger(value)) {
      throw new Error(`${fieldName} number exceeds JavaScript safe integer range; pass a decimal string`);
    }
    return String(value);
  }
  if (typeof value === "string") {
    return value;
  }
  throw new Error(`${fieldName} must be a decimal string, bigint, or safe integer number`);
}

function normalizeRelayer(value) {
  if (value === undefined || value === null) {
    return undefined;
  }
  if (typeof value === "string") {
    return value;
  }
  if (isObject(value)) {
    const standard = value.Standard ?? value.standard;
    const vm = value.Vm ?? value.vm;
    if (standard !== undefined && vm !== undefined) {
      throw new Error("relayer object must include either Standard or Vm, not both");
    }
    if (standard !== undefined) {
      return standard;
    }
    if (vm !== undefined) {
      return vm;
    }
  }
  throw new Error("relayer must be a string, {Standard: string}, {Vm: string}, null, or undefined");
}

export class Warp {
  static transferRemote(args) {
    const relayer = normalizeRelayer(args.relayer);
    return brandCall({
      warp: {
        transfer_remote: makeFields(
          ["warp_route", "destination_domain", "recipient", "amount", "relayer", "gas_payment_limit"],
          [
            args.warpRoute ?? args.warp_route,
            args.destinationDomain ?? args.destination_domain,
            args.recipient,
            normalizeWarpAmount(args.amount, "amount"),
            relayer,
            normalizeWarpAmount(args.gasPaymentLimit ?? args.gas_payment_limit, "gasPaymentLimit"),
          ],
        ),
      },
    });
  }
}
"#;

const WARP_DTS: &str = r#"export interface WarpTransferRemoteArgs {
  warpRoute?: string;
  warp_route?: string;
  amount: string | number | bigint;
  destinationDomain?: number;
  destination_domain?: number;
  gasPaymentLimit?: string | number | bigint;
  gas_payment_limit?: string | number | bigint;
  recipient: string;
  relayer?: { Standard: string } | { standard: string } | { Vm: string } | { vm: string } | string | null;
}

export declare class Warp {
  static transferRemote(args: WarpTransferRemoteArgs): RuntimeCallData;
}
"#;

const TOPICS_JS: &str = r#"// Auto-generated by wasm/build.rs - do not edit manually.
export const OrderbookDepth = Object.freeze({
  D5: "5",
  D10: "10",
  D20: "20",
});

export const KlineInterval = Object.freeze({
  M1: "1m",
  M5: "5m",
  M15: "15m",
  M30: "30m",
  H1: "1h",
  H4: "4h",
  D1: "1d",
});

class TopicData {
  constructor(value) {
    this.value = value;
  }
  toString() {
    return this.value;
  }
}

export class Topic {
  static aggTrade(symbol) {
    return new TopicData(`${symbol}@aggTrade`);
  }
  static depth(symbol, depth) {
    return new TopicData(`${symbol}@depth${depth}`);
  }
  static bookTicker(symbol) {
    return new TopicData(`${symbol}@bookTicker`);
  }
  static markPrice(symbol) {
    return new TopicData(`${symbol}@markPrice`);
  }
  static kline(symbol, interval) {
    return new TopicData(`${symbol}@kline_${interval}`);
  }
  static forceOrder(symbol) {
    return new TopicData(`${symbol}@forceOrder`);
  }
  static userOrders(address) {
    return new TopicData(`${address}@user.orders`);
  }
  static allTickers() {
    return new TopicData("!ticker@arr");
  }
  static allMarkPrices() {
    return new TopicData("!markPrice@arr");
  }
  static allBookTickers() {
    return new TopicData("!bookTicker@arr");
  }
  static allForceOrders() {
    return new TopicData("!forceOrder@arr");
  }
}
"#;

const TOPICS_DTS: &str = r#"// Auto-generated by wasm/build.rs - do not edit manually.
export declare const OrderbookDepth: {
  readonly D5: "5";
  readonly D10: "10";
  readonly D20: "20";
};
export type OrderbookDepth = typeof OrderbookDepth[keyof typeof OrderbookDepth];

export declare const KlineInterval: {
  readonly M1: "1m";
  readonly M5: "5m";
  readonly M15: "15m";
  readonly M30: "30m";
  readonly H1: "1h";
  readonly H4: "4h";
  readonly D1: "1d";
};
export type KlineInterval = typeof KlineInterval[keyof typeof KlineInterval];

export interface TopicData {
  toString(): string;
}

export declare class Topic {
  static aggTrade(symbol: string): TopicData;
  static depth(symbol: string, depth: OrderbookDepth): TopicData;
  static bookTicker(symbol: string): TopicData;
  static markPrice(symbol: string): TopicData;
  static kline(symbol: string, interval: KlineInterval): TopicData;
  static forceOrder(symbol: string): TopicData;
  static userOrders(address: string): TopicData;
  static allTickers(): TopicData;
  static allMarkPrices(): TopicData;
  static allBookTickers(): TopicData;
  static allForceOrders(): TopicData;
}
"#;

const ERRORS_JS: &str = r#"// Auto-generated by wasm/build.rs - do not edit manually.
export { BulletSdkError } from "./bullet-sdk-error.js";

function isObject(value) {
  return typeof value === "object" && value !== null;
}

export function isBulletSdkError(error) {
  return isObject(error)
    && error.name === "BulletSdkError"
    && typeof error.message === "string"
    && typeof error.kind === "string"
    && typeof error.retryable === "boolean";
}

export function asBulletSdkError(error) {
  return isBulletSdkError(error) ? error : undefined;
}
"#;

const ERRORS_DTS: &str = r#"// Auto-generated by wasm/build.rs - do not edit manually.
export {
  BulletSdkError,
} from "./bullet-sdk-error.js";
export type {
  BulletSdkErrorDetails,
  BulletSdkErrorDetailsByKind,
  BulletSdkErrorKind,
  BulletSdkErrorOptions,
  BulletSdkErrorStatus,
  JsonValue as BulletSdkJsonValue,
} from "./bullet-sdk-error.js";
import type { BulletSdkError } from "./bullet-sdk-error.js";

export declare function isBulletSdkError(error: unknown): error is BulletSdkError;
export declare function asBulletSdkError(error: unknown): BulletSdkError | undefined;
"#;
