//! Emit wasm-bindgen wrapper code from parsed progenitor types.

pub mod client;
pub mod types;

use std::collections::HashSet;

use proc_macro2::TokenStream;
use quote::quote;

use super::ProgenitorInfo;

/// Emit the complete generated source file for progenitor wrappers.
pub fn emit_all(info: &ProgenitorInfo) -> String {
    let enum_names: HashSet<&str> = info.enums.iter().map(|e| e.name.as_str()).collect();

    let enum_tokens: Vec<TokenStream> = info.enums.iter().map(types::emit_enum).collect();

    let struct_tokens: Vec<TokenStream> = info
        .structs
        .iter()
        .map(|s| types::emit_struct(s, &enum_names))
        .collect();

    let client_tokens = client::emit_client_impl(&info.methods);

    let tokens = quote! {
        // Auto-generated by build.rs — do not edit manually.
        //
        // Wasm-bindgen wrappers for progenitor-generated REST API types and client methods.

        use bullet_rust_sdk::codegen::types as sdk;
        use wasm_bindgen::prelude::*;

        fn to_json<T: serde::Serialize>(v: &T) -> String {
            serde_json::to_string(v).unwrap_or_else(|_| "{}".to_string())
        }

        #(#enum_tokens)*

        #(#struct_tokens)*

        #client_tokens
    };

    let ast = syn::parse2(tokens).expect("generated progenitor wrapper code should be valid Rust");
    prettyplease::unparse(&ast)
}
