//! Emit wasm-bindgen wrapper code from the CodeModel.
//!
//! This module orchestrates code generation:
//! - `type_map.rs` defines type mappings (the single place to update for new types)
//! - `types.rs` emits struct/enum wrappers using type_map
//! - `client.rs` emits client method wrappers using type_map

pub mod client;
pub mod type_map;
pub mod types;

use std::collections::HashSet;

use proc_macro2::TokenStream;
use quote::quote;

use super::{CodeModel, EnumDetails, MethodDetails, StructDetails, TypeInfo};

/// Emit the complete generated source file for progenitor wrappers.
pub fn emit_all(model: &CodeModel) -> String {
    // Collect enums, structs, and Client methods from the model.
    let mut enums: Vec<&EnumDetails> = Vec::new();
    let mut structs: Vec<&StructDetails> = Vec::new();
    let mut client_methods: Vec<&MethodDetails> = Vec::new();

    for (name, info) in &model.items {
        match info {
            TypeInfo::Enum(e) => enums.push(e),
            TypeInfo::Struct(s) => {
                if name == "Client" {
                    client_methods.extend(&s.methods);
                } else {
                    structs.push(s);
                }
            }
            TypeInfo::Impl(i) if name == "Client" => {
                client_methods.extend(&i.methods);
            }
            TypeInfo::Impl(_) => {}
        }
    }

    // Build enum name set for distinguishing enum refs from struct refs.
    let enum_names: HashSet<&str> = enums.iter().map(|e| e.name.as_str()).collect();

    // Filter to only unit-variant enums (C-style enums usable in wasm-bindgen).
    let unit_enums: Vec<&&EnumDetails> = enums
        .iter()
        .filter(|e| e.variants.iter().all(|v| v.fields.is_empty()))
        .collect();

    let enum_tokens: Vec<TokenStream> = unit_enums.iter().map(|e| types::emit_enum(e)).collect();

    let struct_tokens: Vec<TokenStream> = structs
        .iter()
        .map(|s| types::emit_struct(s, &enum_names))
        .collect();

    let client_tokens = if client_methods.is_empty() {
        quote! {}
    } else {
        client::emit_client_impl(&client_methods, &enum_names)
    };

    let tokens = quote! {
        // Auto-generated by build.rs — do not edit manually.
        //
        // Wasm-bindgen wrappers for progenitor-generated REST API types and client methods.

        use wasm_bindgen::prelude::*;

        fn to_json<T: serde::Serialize>(v: &T) -> String {
            serde_json::to_string(v).unwrap_or_else(|_| "{}".to_string())
        }

        /// Extract elements from a JS Array into a Vec of wrapper types.
        /// Used by client methods that accept array parameters.
        #[allow(dead_code)]
        fn extract_array<T: wasm_bindgen::convert::TryFromJsValue>(
            arr: js_sys::Array,
        ) -> Result<Vec<T>, String> {
            arr.iter()
                .enumerate()
                .map(|(i, v)| {
                    T::try_from_js_value(v)
                        .map_err(|_| format!("invalid element at index {i}"))
                })
                .collect()
        }

        #(#enum_tokens)*

        #(#struct_tokens)*

        #client_tokens
    };

    let ast = syn::parse2(tokens).expect("generated progenitor wrapper code should be valid Rust");
    prettyplease::unparse(&ast)
}
