use heck::{ToLowerCamelCase, ToSnakeCase};

use super::super::super::{ActionGroup, SchemaInfo};
use super::helpers::{
    field_names_array, js_params, js_string, js_values, ordered_fields, ts_param,
};

pub fn emit_calls_js(info: &SchemaInfo) -> String {
    let mut out = String::new();
    out.push_str(CALLS_JS_HEADER);
    out.push('\n');

    for group in &info.action_groups {
        emit_namespace_js(&mut out, group);
        out.push('\n');
    }

    out.push_str(WARP_JS);
    out
}

pub fn emit_calls_dts(info: &SchemaInfo) -> String {
    let mut out = calls_dts_header(info);

    for group in &info.action_groups {
        emit_namespace_dts(&mut out, group);
        out.push('\n');
    }

    out.push_str(WARP_DTS);
    out
}

fn calls_dts_header(info: &SchemaInfo) -> String {
    let imports = info
        .enums
        .iter()
        .map(|e| e.type_name.clone())
        .chain(info.structs.iter().map(|s| s.type_name.clone()))
        .collect::<Vec<_>>()
        .join(", ");

    format!(
        r#"// Auto-generated by wasm/build.rs - do not edit manually.
import type {{ RuntimeCallData }} from "./startup-shared.js";
import type {{ {imports} }} from "./primitives.js";
export type {{ JsonObject, JsonPrimitive, JsonValue, RuntimeCallData }} from "./startup-shared.js";
export {{ isRuntimeCallData, toRuntimeCallJson }} from "./startup-shared.js";

"#
    )
}

fn emit_namespace_js(out: &mut String, group: &ActionGroup) {
    out.push_str(&format!("export class {} {{\n", group.call_message_variant));
    for variant in &group.variants {
        let fields = ordered_fields(&variant.fields);
        let method = variant.variant_name.to_lower_camel_case();
        let action = variant.variant_name.to_snake_case();
        let group_name = group.call_message_variant.to_snake_case();
        let params = js_params(&fields);
        let names = field_names_array(&fields);
        let values = js_values(&fields);

        out.push_str(&format!("  static {method}({params}) {{\n"));
        out.push_str(&format!(
            "    return makeExchangeCall({}, {}, {names}, [{values}]);\n",
            js_string(&group_name),
            js_string(&action)
        ));
        out.push_str("  }\n");
    }
    out.push_str("}\n");
}

fn emit_namespace_dts(out: &mut String, group: &ActionGroup) {
    out.push_str(&format!("export declare class {} {{\n", group.call_message_variant));
    for variant in &group.variants {
        let method = variant.variant_name.to_lower_camel_case();
        let params =
            ordered_fields(&variant.fields).iter().map(ts_param).collect::<Vec<_>>().join(", ");

        out.push_str(&format!("  static {method}({params}): RuntimeCallData;\n"));
    }
    out.push_str("}\n");
}

const CALLS_JS_HEADER: &str = r#"// Auto-generated by wasm/build.rs - do not edit manually.
import { brandCall, isObject, makeFields } from "./startup-shared.js";

export { isRuntimeCallData, toRuntimeCallJson } from "./startup-shared.js";

function makeExchangeCall(group, action, names, values) {
  return brandCall({
    exchange: {
      [group]: {
        [action]: makeFields(names, values),
      },
    },
  });
}
"#;

const WARP_JS: &str = r#"function normalizeWarpAmount(value, fieldName) {
  if (typeof value === "bigint") {
    if (value < 0n) {
      throw new Error(`${fieldName} must be a non-negative integer`);
    }
    return value.toString();
  }
  if (typeof value === "number") {
    if (!Number.isFinite(value) || value < 0 || !Number.isInteger(value)) {
      throw new Error(`${fieldName} number must be a non-negative integer`);
    }
    if (!Number.isSafeInteger(value)) {
      throw new Error(`${fieldName} number exceeds JavaScript safe integer range; pass a decimal string`);
    }
    return String(value);
  }
  if (typeof value === "string") {
    return value;
  }
  throw new Error(`${fieldName} must be a decimal string, bigint, or safe integer number`);
}

function normalizeRelayer(value) {
  if (value === undefined || value === null) {
    return undefined;
  }
  if (typeof value === "string") {
    return value;
  }
  if (isObject(value)) {
    const standard = value.Standard ?? value.standard;
    const vm = value.Vm ?? value.vm;
    if (standard !== undefined && vm !== undefined) {
      throw new Error("relayer object must include either Standard or Vm, not both");
    }
    if (standard !== undefined) {
      return standard;
    }
    if (vm !== undefined) {
      return vm;
    }
  }
  throw new Error("relayer must be a string, {Standard: string}, {Vm: string}, null, or undefined");
}

export class Warp {
  static transferRemote(args) {
    const relayer = normalizeRelayer(args.relayer);
    return brandCall({
      warp: {
        transfer_remote: makeFields(
          ["warp_route", "destination_domain", "recipient", "amount", "relayer", "gas_payment_limit"],
          [
            args.warpRoute ?? args.warp_route,
            args.destinationDomain ?? args.destination_domain,
            args.recipient,
            normalizeWarpAmount(args.amount, "amount"),
            relayer,
            normalizeWarpAmount(args.gasPaymentLimit ?? args.gas_payment_limit, "gasPaymentLimit"),
          ],
        ),
      },
    });
  }
}
"#;

const WARP_DTS: &str = r#"export interface WarpTransferRemoteArgs {
  warpRoute?: string;
  warp_route?: string;
  amount: string | number | bigint;
  destinationDomain?: number;
  destination_domain?: number;
  gasPaymentLimit?: string | number | bigint;
  gas_payment_limit?: string | number | bigint;
  recipient: string;
  relayer?: { Standard: string } | { standard: string } | { Vm: string } | { vm: string } | string | null;
}

export declare class Warp {
  static transferRemote(args: WarpTransferRemoteArgs): RuntimeCallData;
}
"#;
