pub fn emit_errors_js() -> &'static str {
    ERRORS_JS
}

pub fn emit_errors_dts() -> &'static str {
    ERRORS_DTS
}

const ERRORS_JS: &str = r#"// Auto-generated by wasm/build.rs - do not edit manually.
export { BulletSdkError } from "./bullet-sdk-error.js";

function isObject(value) {
  return typeof value === "object" && value !== null;
}

export function isBulletSdkError(error) {
  return isObject(error)
    && error.name === "BulletSdkError"
    && typeof error.message === "string"
    && typeof error.kind === "string"
    && typeof error.retryable === "boolean";
}

export function asBulletSdkError(error) {
  return isBulletSdkError(error) ? error : undefined;
}
"#;

const ERRORS_DTS: &str = r#"// Auto-generated by wasm/build.rs - do not edit manually.
export {
  BulletSdkError,
} from "./bullet-sdk-error.js";
export type {
  BulletSdkErrorDetails,
  BulletSdkErrorDetailsByKind,
  BulletSdkErrorKind,
  BulletSdkErrorOptions,
  BulletSdkErrorStatus,
  JsonValue as BulletSdkJsonValue,
} from "./bullet-sdk-error.js";
import type { BulletSdkError } from "./bullet-sdk-error.js";

export declare function isBulletSdkError(error: unknown): error is BulletSdkError;
export declare function asBulletSdkError(error: unknown): BulletSdkError | undefined;
"#;
