use heck::ToSnakeCase;

use super::super::super::{SchemaEnum, SchemaInfo, SchemaStruct};
use super::helpers::{
    field_names_array, js_params, js_string, js_values, ordered_fields, ts_param, ts_string_literal,
};

pub fn emit_primitives_js(info: &SchemaInfo) -> String {
    let mut out = String::new();
    out.push_str(PRIMITIVES_JS_HEADER);
    out.push('\n');

    for e in &info.enums {
        emit_enum_js(&mut out, e);
        out.push('\n');
    }

    for s in &info.structs {
        emit_struct_js(&mut out, s);
        out.push('\n');
    }

    out
}

pub fn emit_primitives_dts(info: &SchemaInfo) -> String {
    let mut out = String::new();
    out.push_str(PRIMITIVES_DTS_HEADER);
    out.push('\n');

    for e in &info.enums {
        emit_enum_dts(&mut out, e);
        out.push('\n');
    }

    for s in &info.structs {
        emit_struct_dts(&mut out, s);
        out.push('\n');
    }

    out
}

fn emit_enum_js(out: &mut String, e: &SchemaEnum) {
    out.push_str(&format!("export const {} = Object.freeze({{\n", e.type_name));
    for variant in &e.variants {
        out.push_str(&format!("  {}: {},\n", variant, js_string(&variant.to_snake_case())));
    }
    out.push_str("});\n");
}

fn emit_enum_dts(out: &mut String, e: &SchemaEnum) {
    out.push_str(&format!("export declare const {}: {{\n", e.type_name));
    for variant in &e.variants {
        out.push_str(&format!(
            "  readonly {}: {};\n",
            variant,
            ts_string_literal(&variant.to_snake_case())
        ));
    }
    out.push_str("};\n");
    out.push_str(&format!(
        "export type {} = typeof {}[keyof typeof {}];\n",
        e.type_name, e.type_name, e.type_name
    ));
}

fn emit_struct_js(out: &mut String, s: &SchemaStruct) {
    let fields = ordered_fields(&s.fields);
    let params = js_params(&fields);
    let names = field_names_array(&fields);
    let values = js_values(&fields);

    out.push_str(&format!("export class {} {{\n", s.type_name));
    out.push_str(&format!("  constructor({params}) {{\n"));
    out.push_str(&format!("    this.__value = makeFields({names}, [{values}]);\n"));
    out.push_str("    Object.freeze(this.__value);\n");
    out.push_str("  }\n");
    out.push_str("  toJSON() {\n");
    out.push_str("    return this.__value;\n");
    out.push_str("  }\n");
    out.push_str("}\n");
}

fn emit_struct_dts(out: &mut String, s: &SchemaStruct) {
    let params = ordered_fields(&s.fields).iter().map(ts_param).collect::<Vec<_>>().join(", ");

    out.push_str(&format!("export declare class {} {{\n", s.type_name));
    out.push_str(&format!("  constructor({params});\n"));
    out.push_str("  toJSON(): JsonObject;\n");
    out.push_str("}\n");
}

const PRIMITIVES_JS_HEADER: &str = r#"// Auto-generated by wasm/build.rs - do not edit manually.
import { makeFields } from "./startup-shared.js";
"#;

const PRIMITIVES_DTS_HEADER: &str = r#"// Auto-generated by wasm/build.rs - do not edit manually.
export type { JsonObject, JsonPrimitive, JsonValue } from "./startup-shared.js";
import type { JsonObject } from "./startup-shared.js";
"#;
