pub fn emit_shared_js() -> &'static str {
    SHARED_JS
}

pub fn emit_shared_dts() -> &'static str {
    SHARED_DTS
}

const SHARED_JS: &str = r#"// Auto-generated by wasm/build.rs - do not edit manually.
const RUNTIME_CALL_DATA = Symbol.for("@bulletxyz/sdk-wasm/calls/runtime-call");
const MAX_SAFE_INTEGER_BIGINT = BigInt(Number.MAX_SAFE_INTEGER);

export function isObject(value) {
  return typeof value === "object" && value !== null;
}

function isTypedArray(value) {
  return ArrayBuffer.isView(value) && !(value instanceof DataView);
}

function normalizeValue(value) {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  if (typeof value === "bigint") {
    return value;
  }
  if (Array.isArray(value)) {
    return value.map(normalizeValue);
  }
  if (isTypedArray(value)) {
    return Array.from(value);
  }
  if (isObject(value) && typeof value.toJSON === "function") {
    return normalizeValue(value.toJSON());
  }
  if (isObject(value)) {
    const out = {};
    for (const [key, nested] of Object.entries(value)) {
      const normalized = normalizeValue(nested);
      if (normalized !== undefined) {
        out[key] = normalized;
      }
    }
    return out;
  }
  return value;
}

function normalizeForJson(value) {
  const normalized = normalizeValue(value);
  if (typeof normalized === "bigint") {
    if (normalized <= MAX_SAFE_INTEGER_BIGINT && normalized >= -MAX_SAFE_INTEGER_BIGINT) {
      return Number(normalized);
    }
    return normalized.toString();
  }
  if (Array.isArray(normalized)) {
    return normalized.map(normalizeForJson);
  }
  if (isObject(normalized)) {
    const out = {};
    for (const [key, nested] of Object.entries(normalized)) {
      out[key] = normalizeForJson(nested);
    }
    return out;
  }
  return normalized;
}

export function brandCall(value) {
  Object.defineProperty(value, RUNTIME_CALL_DATA, {
    value: true,
    enumerable: false,
  });
  return Object.freeze(value);
}

export function makeFields(names, values) {
  const out = {};
  for (let i = 0; i < names.length; i += 1) {
    const normalized = normalizeValue(values[i]);
    if (normalized !== undefined) {
      out[names[i]] = normalized;
    }
  }
  return out;
}

export function isRuntimeCallData(value) {
  return isObject(value)
    && (value[RUNTIME_CALL_DATA] === true
      || isObject(value.exchange)
      || isObject(value.warp)
      || isObject(value.bank));
}

export function toRuntimeCallJson(call) {
  return JSON.stringify(normalizeForJson(call));
}
"#;

const SHARED_DTS: &str = r#"// Auto-generated by wasm/build.rs - do not edit manually.
export type JsonPrimitive = string | number | boolean | bigint | null;
export type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue };
export type JsonObject = { [key: string]: JsonValue };
export type RuntimeCallData = Readonly<JsonObject> & { readonly __brand?: "RuntimeCallData" };

export declare function isObject(value: unknown): value is { [key: string]: unknown };
export declare function brandCall(value: JsonObject): RuntimeCallData;
export declare function makeFields(names: string[], values: unknown[]): JsonObject;
export declare function isRuntimeCallData(value: unknown): value is RuntimeCallData;
export declare function toRuntimeCallJson(call: RuntimeCallData): string;
"#;
