pub fn emit_topics_js() -> &'static str {
    TOPICS_JS
}

pub fn emit_topics_dts() -> &'static str {
    TOPICS_DTS
}

const TOPICS_JS: &str = r#"// Auto-generated by wasm/build.rs - do not edit manually.
export const OrderbookDepth = Object.freeze({
  D5: "5",
  D10: "10",
  D20: "20",
});

export const KlineInterval = Object.freeze({
  M1: "1m",
  M5: "5m",
  M15: "15m",
  M30: "30m",
  H1: "1h",
  H4: "4h",
  D1: "1d",
});

class TopicData {
  constructor(value) {
    this.value = value;
  }
  toString() {
    return this.value;
  }
}

export class Topic {
  static aggTrade(symbol) {
    return new TopicData(`${symbol}@aggTrade`);
  }
  static depth(symbol, depth) {
    return new TopicData(`${symbol}@depth${depth}`);
  }
  static bookTicker(symbol) {
    return new TopicData(`${symbol}@bookTicker`);
  }
  static markPrice(symbol) {
    return new TopicData(`${symbol}@markPrice`);
  }
  static kline(symbol, interval) {
    return new TopicData(`${symbol}@kline_${interval}`);
  }
  static forceOrder(symbol) {
    return new TopicData(`${symbol}@forceOrder`);
  }
  static userOrders(address) {
    return new TopicData(`${address}@user.orders`);
  }
  static allTickers() {
    return new TopicData("!ticker@arr");
  }
  static allMarkPrices() {
    return new TopicData("!markPrice@arr");
  }
  static allBookTickers() {
    return new TopicData("!bookTicker@arr");
  }
  static allForceOrders() {
    return new TopicData("!forceOrder@arr");
  }
}
"#;

const TOPICS_DTS: &str = r#"// Auto-generated by wasm/build.rs - do not edit manually.
export declare const OrderbookDepth: {
  readonly D5: "5";
  readonly D10: "10";
  readonly D20: "20";
};
export type OrderbookDepth = typeof OrderbookDepth[keyof typeof OrderbookDepth];

export declare const KlineInterval: {
  readonly M1: "1m";
  readonly M5: "5m";
  readonly M15: "15m";
  readonly M30: "30m";
  readonly H1: "1h";
  readonly H4: "4h";
  readonly D1: "1d";
};
export type KlineInterval = typeof KlineInterval[keyof typeof KlineInterval];

export interface TopicData {
  toString(): string;
}

export declare class Topic {
  static aggTrade(symbol: string): TopicData;
  static depth(symbol: string, depth: OrderbookDepth): TopicData;
  static bookTicker(symbol: string): TopicData;
  static markPrice(symbol: string): TopicData;
  static kline(symbol: string, interval: KlineInterval): TopicData;
  static forceOrder(symbol: string): TopicData;
  static userOrders(address: string): TopicData;
  static allTickers(): TopicData;
  static allMarkPrices(): TopicData;
  static allBookTickers(): TopicData;
  static allForceOrders(): TopicData;
}
"#;
